### ISSUE TITLE
Warning: failed to preload PhysX libs

### ISSUE THREAD

**Issue by XIAO6454** [leggedrobotics/legged_gym#21]
**By following the installation procedure, when I tried to run an example `cd examples && python 1080_balls_of_solitude.py` on step 3, it failed:**
(eth) C:\Users\MSI-NB\Desktop\ETH Massive Parallel DRL\ETH_anymal\isaacgym\python\examples>python 1080_balls_of_solitude.py
*** Warning: failed to preload PhysX libs
Traceback (most recent call last):
  File "1080_balls_of_solitude.py", line 25, in <module>
    from isaacgym import gymutil
  File "c:\users\msi-nb\desktop\eth massive parallel drl\eth_anymal\isaacgym\python\isaacgym\__init__.py", line 5, in <module>
    from isaacgym import gymapi
  File "c:\users\msi-nb\desktop\eth massive parallel drl\eth_anymal\isaacgym\python\isaacgym\gymapi.py", line 104, in <module>
    _import_active_version()
  File "c:\users\msi-nb\desktop\eth massive parallel drl\eth_anymal\isaacgym\python\isaacgym\gymapi.py", line 101, in _import_active_version
    raise RuntimeError("No gym module found for the active version of Python (%d.%d)" % (major, minor))
RuntimeError: No gym module found for the active version of Python (3.8)

**So I tried to ignore it and continued following the remaining procedures. After installed all the required packages as instructed, I tried to run 'python train.py --task=anymal_c_flat'. Unfortunatly, same error occured as floows:**
(eth) C:\Users\MSI-NB\Desktop\ETH Massive Parallel DRL\ETH_anymal\legged_gym-master\legged_gym\scripts>python train.py --task=anymal_c_flat --sim_device=cpu --rl_device=cpu --num_envs=4
*** Warning: failed to preload PhysX libs
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    import isaacgym
  File "c:\users\msi-nb\desktop\eth massive parallel drl\eth_anymal\isaacgym\python\isaacgym\__init__.py", line 5, in <module>
    from isaacgym import gymapi
  File "c:\users\msi-nb\desktop\eth massive parallel drl\eth_anymal\isaacgym\python\isaacgym\gymapi.py", line 104, in <module>
    _import_active_version()
  File "c:\users\msi-nb\desktop\eth massive parallel drl\eth_anymal\isaacgym\python\isaacgym\gymapi.py", line 101, in _import_active_version
    raise RuntimeError("No gym module found for the active version of Python (%d.%d)" % (major, minor))
RuntimeError: No gym module found for the active version of Python (3.8)

Does anyone have any idea how to fix this problem?

 - OS: Windows 10 x86_64
 - GPU: RTX 3070 Laptop
 - CUDA: 11.3.109
 - Nvidia Driver: 512.15
 - Torch Version: 1.10.0+cu113

**Comment by XIAO6454** [comment]
Ok, it seems that Isaac Gym only supports Ubuntu 18.04 or 20.04. Check the following link that someone got the same issue:
 https://forums.developer.nvidia.com/t/wsl2-and-isaac-gym-problem/192069/3

**Comment by MerlinRaptor** [comment]
thanks a lot

**Comment by popocheng** [comment]
**Have you solved this problem? I also have the same problem on win10. My python version is 3.8.20. Does gym not support it?**

(gym) E:\gym\competition\competition\legged_gym\legged_gym\scripts>python train.py --task=go2 --num_envs=2048 --headless
*** Warning: failed to preload PhysX libs
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    import isaacgym
  File "e:\gym\competition\competition\isaacgym\python\isaacgym\__init__.py", line 5, in <module>
    from isaacgym import gymapi
  File "e:\gym\competition\competition\isaacgym\python\isaacgym\gymapi.py", line 104, in <module>
    _import_active_version()
  File "e:\gym\competition\competition\isaacgym\python\isaacgym\gymapi.py", line 101, in _import_active_version
    raise RuntimeError("No gym module found for the active version of Python (%d.%d)" % (major, minor))
RuntimeError: No gym module found for the active version of Python (3.8)
