### ISSUE TITLE
    obs, extras = self.env.get_observations() ValueError: too many values to unpack (expected 2)**

### ISSUE THREAD

**Issue by hubuwenxin** [leggedrobotics/legged_gym#59]
**Expected behavior**
When i run the example,  there is error that  :                                                                            
**File "/home/hu/ana/rsl_rl/rsl_rl/runners/on_policy_runner.py", line 29, in __init__
    obs, extras = self.env.get_observations()
ValueError: too many values to unpack (expected 2)**
###################Here is the details#############################
(rl-go2) hu@hu-desktop:~/ana/legged_gym-master$  python3 legged_gym/scripts/train.py --task=anymal_c_flat
Importing module 'gym_38' (/home/hu/ana/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/hu/ana/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.10.0+cu113
Device count 1
/home/hu/ana/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/hu/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Emitting ninja build file /home/hu/.cache/torch_extensions/py38_cu113/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Setting seed: 1
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
/home/hu/.local/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "legged_gym/scripts/train.py", line 47, in <module>
    train(args)
  File "legged_gym/scripts/train.py", line 42, in train
    ppo_runner, train_cfg = task_registry.make_alg_runner(env=env, name=args.task, args=args)
  File "/home/hu/ana/legged_gym-master/legged_gym/utils/task_registry.py", line 147, in make_alg_runner
    runner = OnPolicyRunner(env, train_cfg_dict, log_dir, device=args.rl_device)
  File "/home/hu/ana/rsl_rl/rsl_rl/runners/on_policy_runner.py", line 29, in __init__
    obs, extras = self.env.get_observations()
ValueError: too many values to unpack (expected 2)
################################################

**System (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - GPU: [RTX geforce 2060 ]
 - CUDA: [11.0]
 - GPU Driver: [525.147.05 ]

**Comment by Teddy-Liao** [comment]
same with you!

**Comment by Teddy-Liao** [comment]
It seems that i have figured it out, the "rsl_rl" has been updated, but you should use the old version of "rsl_rl".
Wish you good luck.

**Comment by hubuwenxin** [comment]
when i changed the computer to 3080, everything is fine. It may need more than 8G memory card.

**Comment by laukik29** [comment]
> It seems that i have figured it out, the "rsl_rl" has been updated, but you should use the old version of "rsl_rl". Wish you good luck.

can you please specify the version which worked for you. Thank you.

**Comment by laukik29** [comment]
> when i changed the computer to 3080, everything is fine. It may need more than 8G memory card.

I have 3060ti, which is 8GB memory card, still getting the error.

**Comment by Mayankm96** [comment]
You should use RSL-RL v1.0.2 as mentioned in the readme

> https://github.com/leggedrobotics/legged_gym?tab=readme-ov-file#installation

**Comment by laukik29** [comment]
> You should use RSL-RL v1.0.2 as mentioned in the readme
> 
> > https://github.com/leggedrobotics/legged_gym?tab=readme-ov-file#installation

I am using v1.0.2 and facing the issue.

**Comment by dmtrung14** [comment]
> > You should use RSL-RL v1.0.2 as mentioned in the readme
> > > https://github.com/leggedrobotics/legged_gym?tab=readme-ov-file#installation
> 
> I am using v1.0.2 and facing the issue.

Make sure you have uninstalled v2.0.2 correctly.

**Comment by KevinGrey** [comment]
I downloaded rsl_rl V1.0.2 
fixed

**Comment by liluxing153** [comment]
我是测试是 RSL-RL v1.0.2版本问题，指定 v1.0.2 ，就解决了。使用的是2080super显卡，版本号是470.128
