### ISSUE TITLE
-headless error

### ISSUE THREAD

**Issue by dffsd156** [leggedrobotics/legged_gym#76]
python legged_gym/scripts/train.py --task=anymal_c_flat --sim_device=cuda --rl_device=cuda --pipeline=gpu --num_envs=2048 --headless
Importing module 'gym_38' (/home/song/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/song/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.10.0+cu113
Device count 1
/home/song/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/song/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Emitting ninja build file /home/song/.cache/torch_extensions/py38_cu113/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Setting seed: 1
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
/home/song/anaconda3/envs/isaacgym/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "legged_gym/scripts/train.py", line 47, in <module>
    train(args)
  File "legged_gym/scripts/train.py", line 42, in train
    ppo_runner, train_cfg = task_registry.make_alg_runner(env=env, name=args.task, args=args)
  File "/home/song/legged_gym/legged_gym/utils/task_registry.py", line 147, in make_alg_runner
    runner = OnPolicyRunner(env, train_cfg_dict, log_dir, device=args.rl_device)
  File "/home/song/rsl_rl/rsl_rl/runners/on_policy_runner.py", line 29, in __init__
    obs, extras = self.env.get_observations()
ValueError: too many values to unpack (expected 2)

**My laptop gpu is not good, so I still get a value error even if I use headless, what should I do?**

**Comment by dffsd156** [comment]
In addition, if  num_envs = 32 without headless, the window will exit with a killed phrase
and the reinforcement learning example of Isaac Gym Benchmark Environments worked well by lowering the number value of num_envs 
What's the problem?
